### ISSUE TITLE
Release as a Maven artifact

### ISSUE THREAD

**Issue by brunoborges** [oracle/soda-for-java#1]
Since this is an open source project, can it be released as a Maven artifact on the Public Repository, to be easily integrated on Maven, Gradle, and SBT based projects?

It would also be nice if it could use Travis CI for continuous integration/testing/release process.

**Comment by morgiyan** [comment]
Hi Bruno, we are working on it.. it needs legal approval which takes time. 
I'll check on the status and cc you. Thanks, Max.

**Comment by clausfod** [comment]
What's the status for this ?

**Comment by morgiyan** [comment]
Hi Claus, it's being worked on. We do not have an ETA, but product management/legal told us they are actively working on it. Thanks, Max.

**Comment by clausfod** [comment]
Hi Max, Thanks for the update. 1½ year in the product management/legal department :+1: ;-)

**Comment by gvenzl** [comment]
Hi @clausfod, albeit it looks like it's stuck in a department for such a long period, luckily there has been quite some progress. In the meantime, Oracle and Sonatype are currently working on a partnership that will allow Oracle to put artifacts onto Maven Central to conditions that are inline with Oracle's corporate standards for software delivery and insurance to our customers.

The good news is that once this partnership is in place it will apply for all software and not only this one. However, it is almost impossible to give a concrete ETA for when this is partnership is taking place, as it depends solely on the negotiations and agreement of the two companies.

**Comment by clausfod** [comment]
:+1: Thanks for the answer. We will await this :-)

**Comment by marcelo-ochoa** [comment]
Hi @gvenzl any news on this topic, I mean, is there a plan to release a SODA artifact for Maven??
Best regards, Marcelo.

**Comment by marcelo-ochoa** [comment]
Forget above question, I found it at another package level, https://search.maven.org/search?q=g:com.oracle.database.soda :+1:
