### ISSUE TITLE
missing projection() functionality in soda 1.1.4 for production

### ISSUE THREAD

**Issue by anandpatil** [oracle/soda-for-java#10]
I see the project() feature in the code in OracleOperationBuilderImpl but not made available via the interface. We want to implement something like 
	project().and("testfields.id").as("someid")
that can give use the testfields.id as someid(alias) in the returned query resultset.

Please suggest if there is a plan to release the project functionality soon.

Thanks
Anand

**Comment by morgiyan** [comment]
Hi Anand, projection functionality is on the roadmap. Unfortunately I can't give any concrete ETA. In the meantime, could you simply fetch the document back and extract the values you need on the client-side, using something like [JSONP](https://javaee.github.io/jsonp/)?

Also, could you please tell me what's the intended meaning of:

project().and("testfields.id").as("someid")

Is the intended meaning to extract only the path testfield.id and it's value, and rename the field to "someid" in the resulting document?

**Comment by anandpatil** [comment]
> Hi Anand, projection functionality is on the roadmap. Unfortunately I can't give any concrete ETA. In the meantime, could you simply fetch the document back and extract the values you need on the client-side, using something like [JSONP](https://javaee.github.io/jsonp/)?
> 
> Also, could you please tell me what's the intended meaning of:
> 
> project().and("testfields.id").as("someid")
> 
> Is the intended meaning to extract only the path testfield.id and it's value, and rename the field to "someid" in the resulting document?

**Comment by anandpatil** [comment]
Hi Maxim,
Thanks for looking into this!!
We are migrating a mongo application to Oracle , trying to use the existing queries/Aggregation of Mongo by changing just the DAO layer.
I was able to build the SODA APi source with projection exposed it through the OracleDocumentBuilder interface , also fixed the alias after the retrieval of the resultset.  It is working fine but not aware if there is any problem exposing the project() .
For the alias, you are right.
It will be like  - select testfields.id as someid, testfields.name as somename from testFields;  So the cursor will have fields returned with those alias names from the DB query.
Hope this clarifies the requirement
Thanks,
Anand

**Comment by morgiyan** [comment]
Hi Anand, could you please drop me an email at: 

maxim dot orgiyan at oracle dot com (of course replace "dot" by . and "at" by @. And of course no spaces). 

Or let me know an email address I can contact you at. We can discuss the use of this project. Thanks much!
