### ISSUE TITLE
Publish orajsoda-1.1.7.jar to public maven repository

### ISSUE THREAD

**Issue by aoksenholt** [oracle/soda-for-java#13]
Release 1.1.7 is not available at e.g. mvnrepository.com (lates available release is 1.1.4) - artifacts should be published to public maven repositories for easier access

**Comment by morgiyan** [comment]
Yes, absolutely. That's in progress, should be there soon. I'll update the issue here once it's out.

**Comment by aoksenholt** [comment]
Any update on this?

**Comment by morgiyan** [comment]
Should be there soon, apologies for the delay. I'll keep you posted.

**Comment by morgiyan** [comment]
It's out now: https://repo1.maven.org/maven2/com/oracle/database/soda/orajsoda/1.1.7/

Should be faster from now on. Thanks for your patience.

**Comment by morgiyan** [comment]
1.1.8, which will have the merge method fix, is being finalized and should be out soon.

**Comment by morgiyan** [comment]
There was an issue with 1.1.7 SODA release on Maven Central - an incorrect version for the javax.json dependency was stated in the SODA POM. This is fixed in the 1.1.7.1 SODA patch release on Maven Central, so please use 1.1.7.1 as the latest release version.
